### PR TITLE
Localize toggle for JA locale

### PR DESCRIPTION
**Pull request by iwehrman**
Now it looks like this: 

on

off

Addresses #8.

### CODE REVIEW

**Comment by bchintx** [comment]
To avoid this issue going forward, can you also remove the non-localized .png-s from the img/ folder?

**Comment by iwehrman** [comment]
Nope; they're used in the English locale.

**Comment by bchintx** [comment]
Oh?  Okey dokey.

**Comment by iwehrman** [comment]
en

**Pull request merged**
