### PR TITLE
Fixed Issue #3- "Provide some Guidance About How to Use Edge Inspect"

### PR DESCRIPTION
**Pull request by bchintx**
Fixed Issue #3- "Provide some Guidance About How to Use Edge Inspect"

Adding an extension "how-to" dialog to provide the user with first-run instructions on how to use Edge Inspect.  Implementation based on the EWF extension's implementation of a similar "how-to" dialog.  Similar to EWF, this dialog will appear the first time you click on the Inspect toolbar icon.

From the Inspect extension's UI, you can also view the same dialog using the menu item "Getting started..." in the dropdown that you get from clicking on the "Edge Inspect CC" caption.

The content comes from the Edge Inspect "Getting Started Guide" that displays on first-run in their Chrome Extension.  I altered some of the content to match our implementation within Edge Code.
https://chrome.google.com/webstore/detail/adobe-edge-inspect-cc/ijoeapleklopieoejahbpdnhkjjgddem

### CODE REVIEW

**Comment by bchintx** [comment]
@ryanstewart and/or @iwehrman Can y'all please give this branch a try and let me know if you have any feedback on either the content within the dialog or how the dialog works for you?  Thanks!

**Comment by bchintx** [comment]
edge inspect extension how-to dialog

**Comment by bchintx** [comment]
edge inspect extension getting-started menu item

**Comment by ryanstewart** [comment]
Because points 2 and 3 are related to point 1, I might call them 1, 1a, and 1b. Does that make sense?

**Comment by iwehrman** [comment]
This is great! I think this really improves the usability of the extension. There are a couple of wrinkles that still need to be worked out though. 
1. The modal bleeds off the bottom of a reasonably-sized window: bleed There isn't any way to scroll down when this happens, so the only option is to click the little `x` button. I'm not sure what to do about this. We could either try to manually place the modal higher up in the window, or try to make the modal smaller. Maybe @larz0 has some ideas here. Might also need to talk to the Brackets folks.
2. The modal should only appear the first time the extension icon is ever clicked; not just the first time in a session, which I think is way too often. This should be easy to fix though by storing and loading the firstRun property in the local preferences.
3. I think ideally the popover should _also_ open when the modal is opened, in the background, so when the modal is dismissed it's there waiting for you.  
4. When you open the modal explicitly using the menu in the popover, the menu and popover stay open and cover the modal. cover I think in this case at least the menu should close before opening the modal and probably also the popover. This matches the behavior of the other links that open browser windows.
5. The image in the modal looks like the top-right portion was designed to fade into the background, but our modal backgrounds are grey instead of white. Maybe we can talk @larz0 into making a new image for us in which the top-right fades to transparent instead of white? That would be slick. (I wouldn't consider this a show-stopping issue for this feature though.)

Again, I think this is awesome progress and can't wait to see it in the product. Soon!

**Comment by larz0** [comment]
For the intro, could we use:

"&lt;a href="aam://SAPCode=SHDW?productVersion=1.0.0" target="_blank"&gt;Installing Edge Inspect&lt;a&gt; allows you to preview content across multiple mobile devices. Wirelessly pair multiple iOS and Android devices to your computer, grab screenshots from any connected device, and see real-time results from changes to HTML, CSS, and JavaScript."

**Comment by larz0** [comment]
I'll work on a better image for dialog. Is it possible to use overflow-y: scroll for the content to keep the height shorter?

**Comment by bchintx** [comment]
Pushed a commit incorporating feedback from @larz0 and @ryanstewart.

@larz0 Cool.  Yes, if you have a better image for the dialog, that'd be awesome.  I just pulled one of the images from the Getting Started Guide of Edge Inspect's Chrome Extension.  May I request one that might be a bit shorter in height?

@iwehrman Thanks for the notes.  I tried addressing your first point in my last commit.  The dialog height is now the same as the EWF dialog.  However, now there's a scroll bar within the dialog that you can use to scroll thru the contents.  Y'all lemme know what you think of that approach.  I'll tackle the remaining points next.

**Comment by larz0** [comment]
@bchintx here's the new image at 2x for retina. Just half the actual dimension in : http://cl.ly/04072D341345

I think we can make the instruction less verbose since there are instructions on the phone app and extension, and that there's pretty much only one way to connect. Something like:
1. Install Edge Inspect on the devices and make sure they're are on the same network. Computer and devices must be on the same subnet for auto-discovery.
2. If you can't find the computer on your device, use manual connection (+ button on the device). You can find your computer's IP on the Edge Inspect extension. See image above.
3. Once connected, you'll be able to preview the page on your device. Edge Inspect will prevent the screen from dimming or going to sleep.

Thoughts?

**Comment by bchintx** [comment]
Here's the latest content:  (notice that there's now a scrollbar, so I'll paste two screenshots)
edge inspect extension how-to dialog 1b
edge inspect extension how-to dialog 1a

**Comment by larz0** [comment]
Can we make the intro paragraph text 14px with 20px line-height? Basically the same as .dialog-message. This change should also affect the EWF intro dialog.

**Comment by bchintx** [comment]
updated screenshot for the latest UI
edge inspect extension how-to dialog 2

**Comment by bchintx** [comment]
Quick update: I think I've addressed all of the expressed concerns above except for @iwehrman 's point (3) above.

**Comment by bchintx** [comment]
Fixed the remaining, open issue.  The Getting Started dialog will now appear "on top of" the Inspect extension, both when invoked on first launch and from the extension popup menu.  Once you close the dialog, the Inspect extension popup will remain open.

@iwehrman Ready for review and (hopefully) merge!

**Comment by iwehrman** [comment]
Pushed up a couple little fixes. Looks great, thanks for driving this!

**Comment by bchintx** [comment]
@iwehrman Thanks for the review and (especially) for the z-order fix.  :-)

**Pull request merged**
